### ISSUE TITLE
Routing and Events

### ISSUE THREAD

**Issue by hweeks** [iamezell/thebigneed#1]
What is the advantage of pulling in views to your router, in lieu of sending events through Backbone's event aggregator and having a main plugin to handle this?

Doesn't invoking files from the router violate encapsulation?

On top of all that, How's WebMD? How's your son doing in school now? Ever pick up any of those magic cards?

If you're curious about how I've put together my Backbone apps, check out my attempt at an application framework thingy, [Marionette Framework](https://github.com/hweeks/marionette-framework).

**Comment by iamezell** [comment]
Hey man just saw this, the site is basically a learning project I push views through the router because thats the way I learned to do it. Views are tightly coupled to the router (on router = no views) the views are still encapsulated via the module pattern though, but I feel it should be. I am learning marionette also it seems like a cool framework.
